version: '3'

vars:
  REGISTRY: ghcr.io/ysicing/gitspace-runtime
  TIMESTAMP:
    sh: date -u +'%Y%m%d%H'
  BUILD_DATE:
    sh: date -u +'%Y-%m-%dT%H:%M:%SZ'
  GIT_COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "unknown"
  PLATFORMS: linux/amd64
  VSCODE_EXTENSIONS: "timonwong.shellcheck,shardulm94.trailing-spaces,gruntfuggly.todo-tree,editorconfig.editorconfig,vscode-icons-team.vscode-icons,ms-ceintl.vscode-language-pack-zh-hans"

tasks:
  default:
    desc: 显示帮助信息
    cmds:
      - task --list

  build-base:
    desc: 构建基础镜像
    cmds:
      - |
        docker buildx build \
          --platform {{.PLATFORMS}} \
          --build-arg BUILD_DATE={{.BUILD_DATE}} \
          --build-arg VCS_REF={{.GIT_COMMIT}} \
          -t {{.REGISTRY}}:base-latest \
          -t {{.REGISTRY}}:base-{{.TIMESTAMP}} \
          -f base/Dockerfile \
          --push \
          .

  build-vscode:
    desc: 构建 VSCode Desktop 镜像

    cmds:
      - |
        docker buildx build \
          --platform {{.PLATFORMS}} \
          --build-arg BUILD_DATE={{.BUILD_DATE}} \
          --build-arg VCS_REF={{.GIT_COMMIT}} \
          --build-arg BASE_IMAGE={{.REGISTRY}}:base-latest \
          --build-arg VSCODE_EXTENSIONS="{{.VSCODE_EXTENSIONS}}" \
          -t {{.REGISTRY}}:vscode-latest \
          -t {{.REGISTRY}}:vscode-{{.TIMESTAMP}} \
          -f vscode/Dockerfile \
          --pull \
          --push \
          .

  build-vscode-web:
    desc: 构建 VSCode Web 镜像

    cmds:
      - |
        docker buildx build \
          --platform {{.PLATFORMS}} \
          --build-arg BUILD_DATE={{.BUILD_DATE}} \
          --build-arg VCS_REF={{.GIT_COMMIT}} \
          --build-arg BASE_IMAGE={{.REGISTRY}}:base-latest \
          --build-arg VSCODE_EXTENSIONS="{{.VSCODE_EXTENSIONS}}" \
          -t {{.REGISTRY}}:vscode-web-latest \
          -t {{.REGISTRY}}:vscode-web-{{.TIMESTAMP}} \
          -f vscode-web/Dockerfile \
          --pull \
          --push \
          .

  build-cursor:
    desc: 构建 Cursor 镜像

    cmds:
      - |
        docker buildx build \
          --platform {{.PLATFORMS}} \
          --build-arg BUILD_DATE={{.BUILD_DATE}} \
          --build-arg VCS_REF={{.GIT_COMMIT}} \
          --build-arg BASE_IMAGE={{.REGISTRY}}:base-latest \
          -t {{.REGISTRY}}:cursor-latest \
          -t {{.REGISTRY}}:cursor-{{.TIMESTAMP}} \
          -f cursor/Dockerfile \
          --pull \
          --push \
          .

  build-intellij:
    desc: 构建 IntelliJ IDEA 镜像

    cmds:
      - |
        docker buildx build \
          --platform {{.PLATFORMS}} \
          --build-arg BUILD_DATE={{.BUILD_DATE}} \
          --build-arg VCS_REF={{.GIT_COMMIT}} \
          --build-arg BASE_IMAGE={{.REGISTRY}}:base-latest \
          --build-arg IDE_PRODUCT_CODE=IIC \
          --build-arg IDE_NAME=intellij \
          -t {{.REGISTRY}}:intellij-latest \
          -t {{.REGISTRY}}:intellij-{{.TIMESTAMP}} \
          -f jetbrains/Dockerfile \
          --pull \
          --push \
          .

  build-goland:
    desc: 构建 GoLand 镜像

    cmds:
      - |
        docker buildx build \
          --platform {{.PLATFORMS}} \
          --build-arg BUILD_DATE={{.BUILD_DATE}} \
          --build-arg VCS_REF={{.GIT_COMMIT}} \
          --build-arg BASE_IMAGE={{.REGISTRY}}:base-latest \
          --build-arg IDE_PRODUCT_CODE=GO \
          --build-arg IDE_NAME=goland \
          -t {{.REGISTRY}}:goland-latest \
          -t {{.REGISTRY}}:goland-{{.TIMESTAMP}} \
          -f jetbrains/Dockerfile \
          --pull \
          --push \
          .

  build-pycharm:
    desc: 构建 PyCharm Community 镜像

    cmds:
      - |
        docker buildx build \
          --platform {{.PLATFORMS}} \
          --build-arg BUILD_DATE={{.BUILD_DATE}} \
          --build-arg VCS_REF={{.GIT_COMMIT}} \
          --build-arg BASE_IMAGE={{.REGISTRY}}:base-latest \
          --build-arg IDE_PRODUCT_CODE=PCC \
          --build-arg IDE_NAME=pycharm \
          -t {{.REGISTRY}}:pycharm-latest \
          -t {{.REGISTRY}}:pycharm-{{.TIMESTAMP}} \
          -f jetbrains/Dockerfile \
          --pull \
          --push \
          .

  build-webstorm:
    desc: 构建 WebStorm 镜像

    cmds:
      - |
        docker buildx build \
          --platform {{.PLATFORMS}} \
          --build-arg BUILD_DATE={{.BUILD_DATE}} \
          --build-arg VCS_REF={{.GIT_COMMIT}} \
          --build-arg BASE_IMAGE={{.REGISTRY}}:base-latest \
          --build-arg IDE_PRODUCT_CODE=WS \
          --build-arg IDE_NAME=webstorm \
          -t {{.REGISTRY}}:webstorm-latest \
          -t {{.REGISTRY}}:webstorm-{{.TIMESTAMP}} \
          -f jetbrains/Dockerfile \
          --pull \
          --push \
          .

  build-clion:
    desc: 构建 CLion 镜像

    cmds:
      - |
        docker buildx build \
          --platform {{.PLATFORMS}} \
          --build-arg BUILD_DATE={{.BUILD_DATE}} \
          --build-arg VCS_REF={{.GIT_COMMIT}} \
          --build-arg BASE_IMAGE={{.REGISTRY}}:base-latest \
          --build-arg IDE_PRODUCT_CODE=CL \
          --build-arg IDE_NAME=clion \
          -t {{.REGISTRY}}:clion-latest \
          -t {{.REGISTRY}}:clion-{{.TIMESTAMP}} \
          -f jetbrains/Dockerfile \
          --pull \
          --push \
          .

  build-phpstorm:
    desc: 构建 PHPStorm 镜像

    cmds:
      - |
        docker buildx build \
          --platform {{.PLATFORMS}} \
          --build-arg BUILD_DATE={{.BUILD_DATE}} \
          --build-arg VCS_REF={{.GIT_COMMIT}} \
          --build-arg BASE_IMAGE={{.REGISTRY}}:base-latest \
          --build-arg IDE_PRODUCT_CODE=PS \
          --build-arg IDE_NAME=phpstorm \
          -t {{.REGISTRY}}:phpstorm-latest \
          -t {{.REGISTRY}}:phpstorm-{{.TIMESTAMP}} \
          -f jetbrains/Dockerfile \
          --pull \
          --push \
          .

  build-rubymine:
    desc: 构建 RubyMine 镜像

    cmds:
      - |
        docker buildx build \
          --platform {{.PLATFORMS}} \
          --build-arg BUILD_DATE={{.BUILD_DATE}} \
          --build-arg VCS_REF={{.GIT_COMMIT}} \
          --build-arg BASE_IMAGE={{.REGISTRY}}:base-latest \
          --build-arg IDE_PRODUCT_CODE=RM \
          --build-arg IDE_NAME=rubymine \
          -t {{.REGISTRY}}:rubymine-latest \
          -t {{.REGISTRY}}:rubymine-{{.TIMESTAMP}} \
          -f jetbrains/Dockerfile \
          --pull \
          --push \
          .

  build-rider:
    desc: 构建 Rider 镜像

    cmds:
      - |
        docker buildx build \
          --platform {{.PLATFORMS}} \
          --build-arg BUILD_DATE={{.BUILD_DATE}} \
          --build-arg VCS_REF={{.GIT_COMMIT}} \
          --build-arg BASE_IMAGE={{.REGISTRY}}:base-latest \
          --build-arg IDE_PRODUCT_CODE=RD \
          --build-arg IDE_NAME=rider \
          -t {{.REGISTRY}}:rider-latest \
          -t {{.REGISTRY}}:rider-{{.TIMESTAMP}} \
          -f jetbrains/Dockerfile \
          --pull \
          --push \
          .

  build-jetbrains:
    desc: 构建所有 JetBrains IDE 镜像
    cmds:
      - task: build-intellij
      - task: build-goland
      - task: build-pycharm
      - task: build-webstorm
      - task: build-clion
      - task: build-phpstorm
      - task: build-rubymine
      - task: build-rider

  build-all:
    desc: 构建所有镜像
    cmds:
      - task: build-base
      - task: build-vscode
      - task: build-vscode-web
      - task: build-cursor
      - task: build-jetbrains
