apiVersion: v1
kind: Namespace
metadata:
  name: gitspace-demo

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitspace-jetbrains-pvc
  namespace: gitspace-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitspace-jetbrains
  namespace: gitspace-demo
  labels:
    app: gitspace
    ide: jetbrains
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitspace
      ide: jetbrains
  template:
    metadata:
      labels:
        app: gitspace
        ide: jetbrains
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

      initContainers:
      - name: gitspace-init
        image: gitness/gitspace:jetbrains-latest
        command: ["/usr/local/bin/gitspace-init.sh"]
        env:
        - name: WORKSPACE_DIR
          value: "/workspace"
        - name: REPO_NAME
          value: "my-repo"
        - name: REPO_URL
          value: "https://github.com/example/my-repo.git"
        - name: REPO_BRANCH
          value: "main"
        - name: GIT_USERNAME
          value: "gituser"
        - name: GIT_PASSWORD
          value: "your-git-token"
        - name: IDE_TYPE
          value: "intellij"
        - name: IDE_PORT
          value: "8090"
        - name: GITSPACE_IDENTIFIER
          value: "gitspace-jetbrains-demo"
        # JetBrains 专用配置
        - name: JETBRAINS_IDE_DIR
          value: "/home/vscode/.jetbrains-ide"
        - name: JETBRAINS_PLUGINS
          value: "GitToolBox,com.intellij.java"  # 可选：插件ID列表
        - name: JETBRAINS_JVM_OPTIONS
          value: "-Xmx2048m"  # 可选：JVM 选项
        volumeMounts:
        - name: workspace
          mountPath: /workspace
        - name: shared
          mountPath: /shared

      containers:
      - name: jetbrains-ide
        image: gitness/gitspace:jetbrains-latest
        command: ["/bin/bash", "/shared/start.sh"]
        ports:
        - containerPort: 8090
          name: ide
          protocol: TCP
        env:
        - name: HOME
          value: "/home/vscode"
        - name: WORKSPACE_DIR
          value: "/workspace"
        - name: REPO_NAME
          value: "my-repo"
        - name: IDE_PORT
          value: "8090"
        - name: IDE_TYPE
          value: "intellij"
        volumeMounts:
        - name: workspace
          mountPath: /workspace
        - name: shared
          mountPath: /shared
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"

      volumes:
      - name: workspace
        persistentVolumeClaim:
          claimName: gitspace-jetbrains-pvc
      - name: shared
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: gitspace-jetbrains
  namespace: gitspace-demo
spec:
  selector:
    app: gitspace
    ide: jetbrains
  ports:
  - name: ide
    port: 8090
    targetPort: 8090
    protocol: TCP
  type: LoadBalancer

---
# 可选：Ingress 配置
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: gitspace-jetbrains
#   namespace: gitspace-demo
#   annotations:
#     kubernetes.io/ingress.class: nginx
# spec:
#   rules:
#   - host: jetbrains.gitspace.example.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: gitspace-jetbrains
#             port:
#               number: 8090
