apiVersion: v1
kind: Namespace
metadata:
  name: gitspace-demo

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitspace-vscode-pvc
  namespace: gitspace-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitspace-vscode
  namespace: gitspace-demo
  labels:
    app: gitspace
    ide: vscode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitspace
      ide: vscode
  template:
    metadata:
      labels:
        app: gitspace
        ide: vscode
    spec:
      securityContext:
        # Pod 级别安全上下文
        # fsGroup 确保挂载的卷文件属于此组
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

      initContainers:
      # InitContainer: Gitspace 初始化 (使用预装镜像!)
      - name: gitspace-init
        image: ghcr.io/ysicing/gitspace-runtime:vscode-latest  # 预装 code-server 和所有脚本
        command: ["/bin/bash", "-c"]
        args:
          - |
            set -euo pipefail

            echo "=========================================="
            echo "Gitspace 初始化开始 (使用预装镜像)"
            echo "镜像: ghcr.io/ysicing/gitspace-runtime:vscode-latest"
            echo "=========================================="

            # 检查 code-server 是否预装
            if command -v code-server &> /dev/null; then
                echo "✓ code-server 已预装: $(code-server --version | head -1)"
            else
                echo "⚠️  code-server 未找到"
            fi

            # 检查脚本是否可用
            if [ -d /usr/local/gitspace/scripts/common ]; then
                echo "✓ Docker Gitspace 脚本已加载"
                ls -la /usr/local/gitspace/scripts/common/ | head -5
            fi

            # 确保 HOME 目录权限正确
            HOME_DIR="/home/vscode"
            if [ -d "$HOME_DIR" ]; then
                chown -R 1000:1000 "$HOME_DIR" 2>/dev/null || true
                echo "✓ HOME 目录权限已修复: $HOME_DIR"
            fi

            # 数据迁移: 如果检测到旧的 /workspaces 结构, 迁移到 HOME
            if [ -d "$HOME_DIR" ] && [ -d /mnt/home/workspaces ] && [ ! -L /mnt/home/workspaces ]; then
              echo "[MIGRATE] 检测到旧的 /workspaces 挂载, 开始迁移到 $HOME_DIR ..."
              for item in /mnt/home/workspaces/*; do
                if [ -e "$item" ]; then
                  item_name=$(basename "$item")
                  echo "[MIGRATE]   移动: $item -> $HOME_DIR/$item_name"
                  mv "$item" "$HOME_DIR/" 2>/dev/null || cp -rp "$item" "$HOME_DIR/" || true
                fi
              done
              rm -rf /mnt/home/workspaces 2>/dev/null || true
              echo "[MIGRATE] 迁移完成"
            fi

            # 创建向后兼容的符号链接 /workspaces -> $HOME_DIR
            if [ ! -e /mnt/home/workspaces ]; then
              ln -s "$HOME_DIR" /mnt/home/workspaces || true
              echo "✓ 符号链接已创建: /workspaces -> $HOME_DIR (向后兼容)"
            fi

            # 使用镜像内置的初始化脚本
            if [ -f /usr/local/bin/gitspace-init.sh ]; then
                echo "=========================================="
                echo "执行 Gitspace 初始化脚本..."
                echo "=========================================="
                /usr/local/bin/gitspace-init.sh
            else
                echo "⚠️  初始化脚本未找到,跳过"
            fi

            echo "=========================================="
            echo "✅ Gitspace 初始化完成"
            echo "=========================================="
        env:
        - name: HOME
          value: "/home/vscode"
        - name: USER
          value: "vscode"
        - name: REPO_NAME
          value: "my-repo"
        - name: REPO_URL
          value: "https://github.com/example/my-repo.git"
        - name: BRANCH
          value: "main"
        - name: GIT_USERNAME
          value: "gituser"
        - name: GIT_PASSWORD
          value: "your-git-token"
        - name: IDE_TYPE
          value: "vscode-web"
        - name: IDE_PORT
          value: "8089"
        - name: GITSPACE_IDENTIFIER
          value: "gitspace-vscode-demo"
        volumeMounts:
        - name: home
          mountPath: /mnt/home  # InitContainer 使用临时挂载点修复权限
        - name: shared
          mountPath: /shared
        securityContext:
          runAsUser: 0  # InitContainer 需要 root 权限修复权限

      containers:
      - name: vscode-ide
        image: ghcr.io/ysicing/gitspace-runtime:vscode-latest  # 使用预装镜像
        command: ["/bin/bash", "-c"]
        args:
          - |
            set -e

            echo "=========================================="
            echo "启动 VSCode Server (code-server 已预装!)"
            echo "=========================================="

            # 检查 code-server
            code-server --version | head -1

            # 确认仓库路径
            REPO_PATH="$HOME/${REPO_NAME}"
            if [ -d "$REPO_PATH" ]; then
                echo "✓ 仓库已存在: $REPO_PATH"
                cd "$REPO_PATH"
            else
                echo "⚠️  仓库不存在: $REPO_PATH, 使用 HOME: $HOME"
                cd "$HOME"
            fi

            # 创建 code-server 配置
            CONFIG_DIR="$HOME/.config/code-server"
            mkdir -p "$CONFIG_DIR"

            cat > "$CONFIG_DIR/config.yaml" <<EOF
            bind-addr: 0.0.0.0:${IDE_PORT}
            auth: none
            cert: false
            EOF

            echo "✓ 配置文件: $CONFIG_DIR/config.yaml"
            echo "✓ 工作目录: $(pwd)"
            echo "✓ 端口: ${IDE_PORT}"
            echo "=========================================="
            echo "✅ 启动 code-server..."
            echo "=========================================="

            # 启动 code-server (已预装,无需下载!)
            exec code-server --disable-workspace-trust "$(pwd)"
        ports:
        - containerPort: 8089
          name: ide
          protocol: TCP
        env:
        - name: HOME
          value: "/home/vscode"
        - name: USER
          value: "vscode"
        - name: REPO_NAME
          value: "my-repo"
        - name: IDE_PORT
          value: "8089"
        - name: IDE_TYPE
          value: "vscode-web"
        volumeMounts:
        - name: home
          mountPath: /home/vscode  # 挂载到 HOME 目录 (对齐 Docker Gitspace)
        - name: shared
          mountPath: /shared
        workingDir: /home/vscode   # 工作目录 = HOME (对齐 Docker Gitspace)
        securityContext:
          runAsUser: 1000           # 以 vscode 用户运行
          runAsGroup: 1000
          allowPrivilegeEscalation: false
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"

      volumes:
      - name: home                  # 卷名称改为 home
        persistentVolumeClaim:
          claimName: gitspace-vscode-pvc
      - name: shared
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: gitspace-vscode
  namespace: gitspace-demo
spec:
  selector:
    app: gitspace
    ide: vscode
  ports:
  - name: ide
    port: 8089
    targetPort: 8089
    protocol: TCP
  type: LoadBalancer

---
# 可选：Ingress 配置
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: gitspace-vscode
#   namespace: gitspace-demo
#   annotations:
#     kubernetes.io/ingress.class: nginx
# spec:
#   rules:
#   - host: vscode.gitspace.example.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: gitspace-vscode
#             port:
#               number: 8089
