# Gitspace VSCode - ä½¿ç”¨é¢„è£…é•œåƒ (å¿«é€Ÿå¯åŠ¨ç‰ˆ)
#
# å…³é”®ç‰¹æ€§:
# 1. âœ… ä½¿ç”¨é¢„è£… code-server çš„é•œåƒ (ghcr.io/ysicing/gitspace-runtime:vscode-latest)
# 2. âœ… å¯åŠ¨æ—¶é—´ä»Ž 3-5 åˆ†é’Ÿé™è‡³ 30-60 ç§’
# 3. âœ… ç¦»çº¿å¯ç”¨ (æ— éœ€ä¸‹è½½ IDE)
# 4. âœ… ä¸Ž Docker Gitspace 100% è¡Œä¸ºä¸€è‡´
#
# ä½¿ç”¨æ–¹æ³•:
#   kubectl apply -f gitspace-vscode-prebuilt.yaml
#   kubectl wait --for=condition=Ready pod -l app=gitspace -n gitspace-demo --timeout=300s
#   kubectl port-forward -n gitspace-demo svc/gitspace-vscode 8089:8089
#
# è®¿é—®: http://localhost:8089

apiVersion: v1
kind: Namespace
metadata:
  name: gitspace-demo

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitspace-vscode-pvc
  namespace: gitspace-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitspace-vscode
  namespace: gitspace-demo
  labels:
    app: gitspace
    ide: vscode
    version: prebuilt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitspace
      ide: vscode
  template:
    metadata:
      labels:
        app: gitspace
        ide: vscode
        version: prebuilt
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

      initContainers:
      - name: gitspace-init
        image: ghcr.io/ysicing/gitspace-runtime:vscode-latest
        command: ["/bin/bash", "-c"]
        args:
          - |
            set -euo pipefail

            echo "=========================================="
            echo "ðŸš€ Gitspace åˆå§‹åŒ– (ä½¿ç”¨é¢„è£…é•œåƒ)"
            echo "=========================================="

            # éªŒè¯ code-server å·²é¢„è£…
            if command -v code-server &> /dev/null; then
                echo "âœ… code-server: $(code-server --version | head -1)"
            fi

            # éªŒè¯è„šæœ¬å·²åŠ è½½
            if [ -d /usr/local/gitspace/scripts/common ]; then
                echo "âœ… Docker Gitspace è„šæœ¬: å·²åŠ è½½"
            fi

            # ä¿®å¤ HOME ç›®å½•æƒé™
            chown -R 1000:1000 /mnt/home 2>/dev/null || true

            # æ‰§è¡Œåˆå§‹åŒ–è„šæœ¬ (å…‹éš†ä»£ç ã€é…ç½® Git ç­‰)
            if [ -f /usr/local/bin/gitspace-init.sh ]; then
                /usr/local/bin/gitspace-init.sh
            fi

            echo "âœ… åˆå§‹åŒ–å®Œæˆ"
        env:
        - name: HOME
          value: "/home/vscode"
        - name: REPO_NAME
          value: "test"
        - name: REPO_URL
          value: "https://github.com/ysicing/demo.git"
        - name: BRANCH
          value: "main"
        - name: IDE_PORT
          value: "8089"
        volumeMounts:
        - name: home
          mountPath: /mnt/home
        - name: shared
          mountPath: /shared
        securityContext:
          runAsUser: 0

      containers:
      - name: vscode-ide
        image: ghcr.io/ysicing/gitspace-runtime:vscode-latest
        command: ["/bin/bash", "-c"]
        args:
          - |
            set -e

            echo "=========================================="
            echo "ðŸš€ å¯åŠ¨ VSCode Server (å·²é¢„è£…!)"
            echo "=========================================="

            code-server --version | head -1

            # åˆ‡æ¢åˆ°ä»“åº“ç›®å½•
            if [ -d "$HOME/${REPO_NAME}" ]; then
                cd "$HOME/${REPO_NAME}"
                echo "âœ… å·¥ä½œç›®å½•: $HOME/${REPO_NAME}"
            else
                cd "$HOME"
                echo "âš ï¸  ä½¿ç”¨ HOME: $HOME"
            fi

            # é…ç½® code-server
            mkdir -p "$HOME/.config/code-server"
            cat > "$HOME/.config/code-server/config.yaml" <<EOF
            bind-addr: 0.0.0.0:${IDE_PORT}
            auth: none
            cert: false
            EOF

            echo "âœ… ç«¯å£: ${IDE_PORT}"
            echo "âœ… å¯åŠ¨ä¸­..."

            # å¯åŠ¨ code-server (æ— éœ€ä¸‹è½½!)
            exec code-server --disable-workspace-trust "$(pwd)"
        ports:
        - containerPort: 8089
          name: ide
        env:
        - name: HOME
          value: "/home/vscode"
        - name: REPO_NAME
          value: "test"
        - name: IDE_PORT
          value: "8089"
        volumeMounts:
        - name: home
          mountPath: /home/vscode
        - name: shared
          mountPath: /shared
        workingDir: /home/vscode
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"

      volumes:
      - name: home
        persistentVolumeClaim:
          claimName: gitspace-vscode-pvc
      - name: shared
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: gitspace-vscode
  namespace: gitspace-demo
spec:
  selector:
    app: gitspace
    ide: vscode
  ports:
  - name: ide
    port: 8089
    targetPort: 8089
  type: LoadBalancer
