name: Build and Push Images

on:
  # 推送到主分支时触发
  push:
    branches: [ master, main ]

env:
  REGISTRY: ghcr.io/ysicing/gitspace-runtime
  TIMESTAMP: ${{ github.run_id }}
  VSCODE_EXTENSIONS: "timonwong.shellcheck,shardulm94.trailing-spaces,gruntfuggly.todo-tree,editorconfig.editorconfig,vscode-icons-team.vscode-icons,ms-ceintl.vscode-language-pack-zh-hans,redhat.vscode-yaml,waderyan.gitblame,mhutchie.git-graph,donjayamanne.githistory,cnbcool.cnb-welcome,esbenp.prettier-vscode,ms-vscode.vscode-json"

jobs:
  build-and-push:
    name: Build and Push Images
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 登录到 ghcr.io
      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 构建并推送基础镜像
      - name: Build and push base image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./base/Dockerfile
          push: true
          tags: |
            {{ env.REGISTRY }}:base-${{ env.TIMESTAMP }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 构建并推送VSCode镜像
      - name: Build and push VSCode image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./vscode/Dockerfile
          push: true
          tags: |
            {{ env.REGISTRY }}:vscode-${{ env.TIMESTAMP }}
          build-args: |
            BASE_IMAGE={{ env.REGISTRY }}:base-${{ env.TIMESTAMP }}
            VSCODE_EXTENSIONS={{ env.VSCODE_EXTENSIONS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 构建并推送JetBrains镜像
      - name: Build and push JetBrains image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./jetbrains/Dockerfile
          push: true
          tags: |
            {{ env.REGISTRY }}:jetbrains-${{ env.TIMESTAMP }}
          build-args: |
            BASE_IMAGE={{ env.REGISTRY }}:base-${{ env.TIMESTAMP }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 构建并推送Cursor镜像
      - name: Build and push Cursor image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./cursor/Dockerfile
          push: true
          tags: |
            {{ env.REGISTRY }}:cursor-${{ env.TIMESTAMP }}
          build-args: |
            VSCODE_IMAGE={{ env.REGISTRY }}:vscode-${{ env.TIMESTAMP }}
            VSCODE_EXTENSIONS={{ env.VSCODE_EXTENSIONS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 设置 latest 标签
      - name: Tag latest images
        run: |
          echo "设置 latest 标签..."
          docker pull {{ env.REGISTRY }}:base-${{ env.TIMESTAMP }}
          docker pull {{ env.REGISTRY }}:vscode-${{ env.TIMESTAMP }}
          docker pull {{ env.REGISTRY }}:jetbrains-${{ env.TIMESTAMP }}
          docker pull {{ env.REGISTRY }}:cursor-${{ env.TIMESTAMP }}
          docker tag {{ env.REGISTRY }}:base-${{ env.TIMESTAMP }} {{ env.REGISTRY }}:base-latest
          docker tag {{ env.REGISTRY }}:vscode-${{ env.TIMESTAMP }} {{ env.REGISTRY }}:vscode-latest
          docker tag {{ env.REGISTRY }}:jetbrains-${{ env.TIMESTAMP }} {{ env.REGISTRY }}:jetbrains-latest
          docker tag {{ env.REGISTRY }}:cursor-${{ env.TIMESTAMP }} {{ env.REGISTRY }}:cursor-latest
          docker push {{ env.REGISTRY }}:base-latest
          docker push {{ env.REGISTRY }}:vscode-latest
          docker push {{ env.REGISTRY }}:jetbrains-latest
          docker push {{ env.REGISTRY }}:cursor-latest

      # 显示镜像信息
      - name: Show Image Info
        run: |
          echo "================================"
          echo "✓ 构建并推送完成!"
          echo "================================"
          echo "Registry: {{ env.REGISTRY }}"
          echo "镜像标签: {{ env.TIMESTAMP }}"
          echo ""
          echo "镜像地址:"
          echo "  - {{ env.REGISTRY }}:base-{{ env.TIMESTAMP }}"
          echo "  - {{ env.REGISTRY }}:vscode-{{ env.TIMESTAMP }}"
          echo "  - {{ env.REGISTRY }}:jetbrains-{{ env.TIMESTAMP }}"
          echo "  - {{ env.REGISTRY }}:cursor-{{ env.TIMESTAMP }}"
          if [ -n "{{ env.VSCODE_EXTENSIONS }}" ]; then
            echo ""
            echo "VSCode 扩展: {{ env.VSCODE_EXTENSIONS }}"
          fi
          echo ""
          echo "测试命令:"
          echo "  docker run --rm {{ env.REGISTRY }}:vscode-{{ env.TIMESTAMP }} --version"
          echo "  docker run --rm {{ env.REGISTRY }}:base-{{ env.TIMESTAMP }} which git"
